### ISSUE TITLE
Wrong reference for RV1 and RV2 in BOM

### ISSUE THREAD

**Issue by laurent-fr** [schlae/FloppyExerciser#1]
Hi !

In BOM, RV1 and RV2 should be 3386P-1-202TLF instead of 3386F-1-202TLF (wrong footprint - https://www.bourns.com/docs/Product-Datasheets/3386.pdf)

thanks !

**Comment by schlae** [comment]
Fixed: https://github.com/schlae/FloppyExerciser/commit/7e459499f52b082e0d4a15c8c32506de48172900

**Comment by laurent-fr** [comment]
thx :-)
